services:
  db:
    image: mysql:8.0.36
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat_system_development
  redis:
    image: redis
    ports:
      - '6379:6379'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
  web:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - elasticsearch
    restart: on-failure
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: mysql2://root:123456@db/chat_system_development
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    extra_hosts: 
      - "www.example.com=127.0.0.1"
  sidekiq:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - '3001:3000'
    depends_on:
      - db
      - redis
      - elasticsearch
    restart: on-failure
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: mysql2://root:123456@db/chat_system_development
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    extra_hosts: 
      - "www.example.com=127.0.0.1"
volumes:
  mysql_data: {}
  bundle_cache: {}
